# Fails unless libgtk4-layer-shell comes before libwayland-client in BINARY's
# NEEDED entries. When the binary does not name libwayland-client itself, the
# layer-shell library is still loaded before GTK pulls it in, which is enough.
execute_process(COMMAND ${READELF} -d ${BINARY}
                OUTPUT_VARIABLE dyn RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "readelf -d ${BINARY} failed")
endif()
string(REGEX MATCHALL "\\(NEEDED\\)[^\n]*\\[[^]]+\\]" needed "${dyn}")
set(pos 0)
set(layer -1)
set(wayland -1)
set(gtk -1)
foreach(line IN LISTS needed)
  if(line MATCHES "libgtk4-layer-shell" AND layer EQUAL -1)
    set(layer ${pos})
  elseif(line MATCHES "libwayland-client" AND wayland EQUAL -1)
    set(wayland ${pos})
  elseif(line MATCHES "libgtk-4" AND gtk EQUAL -1)
    set(gtk ${pos})
  endif()
  math(EXPR pos "${pos} + 1")
endforeach()
if(layer EQUAL -1)
  message(FATAL_ERROR "libgtk4-layer-shell is not in the NEEDED list")
endif()
if(NOT wayland EQUAL -1 AND wayland LESS layer)
  message(FATAL_ERROR "libwayland-client (${wayland}) is NEEDED before libgtk4-layer-shell (${layer})")
endif()
if(NOT gtk EQUAL -1 AND gtk LESS layer)
  message(FATAL_ERROR "libgtk-4 (${gtk}) is NEEDED before libgtk4-layer-shell (${layer})")
endif()
message(STATUS "link order ok: layer-shell ${layer}, gtk ${gtk}, wayland-client ${wayland}")
